#!/bin/bash
#SBATCH -J myjob # Job name
#SBATCH -o myjob.o%j # Name of stdout output file
#SBATCH -e myjob.e%j # Name of stderr error file
#SBATCH -p normal # Queue (partition) name
#SBATCH -N 4 # Total # of nodes
#SBATCH -n 272 # Total # ask for 272  cores on a node
#SBATCH -t 02:00:00 # Run time (hh:mm:ss)
#SBATCH --mail-user=mgadupudi@umassd.edu
#SBATCH --mail-type=all
# Send email at begin and end of job
ibrun ./optimizer 100000

